apiVersion: v1
kind: ConfigMap
metadata:
  name: tg-captcha-bot-configmap
data:
  config.toml: |
    # Config file for Telegram Captcha Bot

    # Button text
    button_text = "Human"

    # Bot sends this message to new users
    welcome_message = "Hello! I'm Bot'ish, the spam protection system. Please press the Human button within 15 seconds or you will be banned!"

    # Edit welcome message with this text if user passed validation
    after_success_message = "ğŸ‘ âœ… ğŸ‰"

    # Edit welcome message with this text if user failed validation
    after_fail_message = "ğŸ‘ ğŸš« ğŸ¤–"

    # Show success and failure messages or delete them. Pick "show" or "del"
    print_success_and_fail_messages_strategy = "show"
